import type {
  AISummary,
  Notification,
  Profile,
  Resource,
  User,
  Workspace,
} from '../types';
import { TAGS } from '../constants';

export const mockUser: User = {
  id: 'u1',
  name: 'Alex Morgan',
  email: 'alex.morgan@research.io',
  avatarUrl: 'https://images.pexels.com/photos/220817/pexels-photo-220817.jpeg?auto=compress&cs=tinysrgb&w=200',
  role: 'owner',
  joinedDate: '2024-01-15T08:00:00Z',
};

export const mockWorkspaces: Workspace[] = [
  {
    id: 'ws1',
    title: 'AI Safety Research',
    description: 'Tracking alignment, interpretability, and governance research across leading labs.',
    createdAt: '2024-02-10T09:30:00Z',
    owner: 'Alex Morgan',
    ownerId: 'u1',
    color: 'from-primary-500 to-accent-500',
    icon: 'ShieldCheck',
    resourceCount: 24,
    summaryCount: 18,
    members: [
      { id: 'u1', name: 'Alex Morgan', email: 'alex.morgan@research.io', avatarUrl: mockUser.avatarUrl, role: 'owner' },
      { id: 'u2', name: 'Priya Sharma', email: 'priya@research.io', avatarUrl: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=200', role: 'member' },
      { id: 'u3', name: 'Daniel Kim', email: 'daniel@research.io', avatarUrl: 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=200', role: 'member' },
    ],
  },
  {
    id: 'ws2',
    title: 'Distributed Systems',
    description: 'Papers and talks on consensus, storage engines, and large-scale infrastructure.',
    createdAt: '2024-03-04T14:15:00Z',
    owner: 'Alex Morgan',
    ownerId: 'u1',
    color: 'from-emerald-500 to-teal-500',
    icon: 'Server',
    resourceCount: 31,
    summaryCount: 22,
    members: [
      { id: 'u1', name: 'Alex Morgan', email: 'alex.morgan@research.io', avatarUrl: mockUser.avatarUrl, role: 'owner' },
      { id: 'u4', name: 'Sara Chen', email: 'sara@research.io', avatarUrl: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=200', role: 'member' },
    ],
  },
  {
    id: 'ws3',
    title: 'Product Strategy 2025',
    description: 'Market analysis, competitive teardowns, and roadmap thinking for next year.',
    createdAt: '2024-05-22T11:00:00Z',
    owner: 'Alex Morgan',
    ownerId: 'u1',
    color: 'from-amber-500 to-orange-500',
    icon: 'Target',
    resourceCount: 16,
    summaryCount: 9,
    members: [
      { id: 'u1', name: 'Alex Morgan', email: 'alex.morgan@research.io', avatarUrl: mockUser.avatarUrl, role: 'owner' },
      { id: 'u5', name: 'Marcus Lee', email: 'marcus@research.io', avatarUrl: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=200', role: 'viewer' },
    ],
  },
  {
    id: 'ws4',
    title: 'NLP & Transformers',
    description: 'Foundational and frontier work on language models, retrieval, and agents.',
    createdAt: '2024-06-18T16:45:00Z',
    owner: 'Alex Morgan',
    ownerId: 'u1',
    color: 'from-violet-500 to-purple-500',
    icon: 'BrainCircuit',
    resourceCount: 42,
    summaryCount: 35,
    members: [
      { id: 'u1', name: 'Alex Morgan', email: 'alex.morgan@research.io', avatarUrl: mockUser.avatarUrl, role: 'owner' },
      { id: 'u2', name: 'Priya Sharma', email: 'priya@research.io', avatarUrl: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=200', role: 'member' },
      { id: 'u6', name: 'Lena Park', email: 'lena@research.io', avatarUrl: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200', role: 'member' },
    ],
  },
];

export const mockResources: Resource[] = [
  {
    id: 'r1',
    workspaceId: 'ws1',
    title: 'Constitutional AI: Harmlessness from AI Feedback',
    type: 'article',
    sourceUrl: 'https://anthropic.com/constitutional-ai',
    sourceName: 'anthropic.com',
    description: 'A method for training language models to be harmless and helpful using AI feedback rather than human labels.',
    tags: [TAGS.ai, TAGS.research, TAGS.security],
    dateAdded: '2024-07-01T10:20:00Z',
    status: 'completed',
    author: 'Anthropic',
    readTimeMinutes: 18,
    thumbnailUrl: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'r2',
    workspaceId: 'ws1',
    title: 'Interpretability in the Wild: Circuit Analysis',
    type: 'video',
    sourceUrl: 'https://youtube.com/watch?v=interpretability',
    sourceName: 'youtube.com',
    description: 'A deep dive into mechanistic interpretability and reverse-engineering neural networks.',
    tags: [TAGS.ai, TAGS.ml],
    dateAdded: '2024-07-03T13:00:00Z',
    status: 'reading',
    author: 'Neel Nanda',
    durationSeconds: 2840,
    thumbnailUrl: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'r3',
    workspaceId: 'ws1',
    title: 'Notes: Alignment Taxonomy v2',
    type: 'note',
    sourceUrl: '',
    sourceName: 'Local note',
    description: 'Personal notes mapping the alignment problem space — outer vs inner, capability vs safety.',
    tags: [TAGS.research, TAGS.ai],
    dateAdded: '2024-07-05T09:15:00Z',
    status: 'unread',
    author: 'Alex Morgan',
  },
  {
    id: 'r4',
    workspaceId: 'ws2',
    title: 'The Raft Consensus Algorithm',
    type: 'article',
    sourceUrl: 'https://raft.github.io',
    sourceName: 'raft.github.io',
    description: 'Understandable consensus algorithm designed as an alternative to Paxos for replicated state machines.',
    tags: [TAGS.systems, TAGS.research],
    dateAdded: '2024-06-20T11:30:00Z',
    status: 'completed',
    author: 'Diego Ongaro',
    readTimeMinutes: 25,
    thumbnailUrl: 'https://images.pexels.com/photos/1181271/pexels-photo-1181271.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'r5',
    workspaceId: 'ws2',
    title: 'Designing Data-Intensive Applications — Ch. 7',
    type: 'article',
    sourceUrl: 'https://dataintensive.net',
    sourceName: 'dataintensive.net',
    description: 'Transaction isolation levels and the anomalies they prevent, with practical examples.',
    tags: [TAGS.systems, TAGS.data],
    dateAdded: '2024-06-25T15:45:00Z',
    status: 'reading',
    author: 'Martin Kleppmann',
    readTimeMinutes: 32,
    thumbnailUrl: 'https://images.pexels.com/photos/1181271/pexels-photo-1181271.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'r6',
    workspaceId: 'ws3',
    title: 'How Linear builds product',
    type: 'video',
    sourceUrl: 'https://youtube.com/watch?v=linear-product',
    sourceName: 'youtube.com',
    description: 'Karri Saarinen on craft, taste, and building software with opinionated defaults.',
    tags: [TAGS.product, TAGS.webdev],
    dateAdded: '2024-07-02T08:00:00Z',
    status: 'unread',
    author: 'Karri Saarinen',
    durationSeconds: 3600,
    thumbnailUrl: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'r7',
    workspaceId: 'ws4',
    title: 'Attention Is All You Need',
    type: 'article',
    sourceUrl: 'https://arxiv.org/abs/1706.03762',
    sourceName: 'arxiv.org',
    description: 'The original Transformer paper introducing the self-attention mechanism.',
    tags: [TAGS.nlp, TAGS.ai, TAGS.research],
    dateAdded: '2024-06-12T10:00:00Z',
    status: 'completed',
    author: 'Vaswani et al.',
    readTimeMinutes: 22,
    thumbnailUrl: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'r8',
    workspaceId: 'ws4',
    title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP',
    type: 'article',
    sourceUrl: 'https://arxiv.org/abs/2005.11401',
    sourceName: 'arxiv.org',
    description: 'RAG models combining parametric and non-parametric memory for open-domain QA.',
    tags: [TAGS.nlp, TAGS.ai, TAGS.data],
    dateAdded: '2024-06-28T14:20:00Z',
    status: 'reading',
    author: 'Lewis et al.',
    readTimeMinutes: 28,
    thumbnailUrl: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
  {
    id: 'r9',
    workspaceId: 'ws4',
    title: 'Notes: Agent architectures comparison',
    type: 'note',
    sourceUrl: '',
    sourceName: 'Local note',
    description: 'ReAct, Reflexion, and Plan-and-Execute — when each pattern wins.',
    tags: [TAGS.ai, TAGS.nlp],
    dateAdded: '2024-07-04T17:10:00Z',
    status: 'unread',
    author: 'Alex Morgan',
  },
  {
    id: 'r10',
    workspaceId: 'ws3',
    title: 'The Pragmatic Engineer: Roadmap pitfalls',
    type: 'article',
    sourceUrl: 'https://newsletter.pragmaticengineer.com',
    sourceName: 'newsletter.pragmaticengineer.com',
    description: 'Common anti-patterns in annual planning and how strong teams avoid them.',
    tags: [TAGS.product],
    dateAdded: '2024-07-06T07:30:00Z',
    status: 'unread',
    author: 'Gergely Orosz',
    readTimeMinutes: 12,
    thumbnailUrl: 'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=600',
  },
];

export const mockSummaries: AISummary[] = [
  {
    id: 's1',
    resourceId: 'r1',
    resourceTitle: 'Constitutional AI: Harmlessness from AI Feedback',
    workspaceId: 'ws1',
    workspaceName: 'AI Safety Research',
    title: 'Constitutional AI — Core Method',
    summary:
      'Constitutional AI (CAI) trains helpful and harmless assistants by replacing human preference labels with AI-generated feedback. A model critiques its own outputs against a set of natural-language principles (a "constitution"), revises accordingly, and the revised pairs become preference data for RLHF. This reduces the human label burden while producing models that are less evasive and more transparent about their reasoning.',
    keyTakeaways: [
      { id: 'k1', text: 'CAI uses a written constitution of principles rather than pure human ratings to steer behavior.' },
      { id: 'k2', text: 'Self-critique + revision generates synthetic preference pairs for reinforcement learning.' },
      { id: 'k3', text: 'Reduces label cost substantially while improving transparency of reasoning.' },
      { id: 'k4', text: 'Models become less evasive — they engage with sensitive topics rather than refusing outright.' },
    ],
    importantQuotes: [
      { id: 'q1', text: 'The central idea is to use a model to evaluate and improve the behavior of another model (or itself), guided by a set of principles.', page: 2 },
      { id: 'q2', text: 'CAI models are less evasive and more transparent than RLHF models trained on human feedback alone.' },
    ],
    suggestedQuestions: [
      'How does CAI compare to DPO in terms of sample efficiency?',
      'What principles are most effective at reducing sycophancy?',
      'Can the constitution itself be learned rather than hand-authored?',
    ],
    generatedDate: '2024-07-01T11:00:00Z',
    tags: [TAGS.ai, TAGS.research, TAGS.security],
    model: 'rw-summarizer-v2',
  },
  {
    id: 's2',
    resourceId: 'r4',
    resourceTitle: 'The Raft Consensus Algorithm',
    workspaceId: 'ws2',
    workspaceName: 'Distributed Systems',
    title: 'Raft — Leader-Based Consensus',
    summary:
      'Raft is a consensus algorithm for managing a replicated log, designed for understandability. It decomposes consensus into three subproblems: leader election, log replication, and safety. A single elected leader handles all client writes, replicating entries to followers; if the leader fails, followers elect a new one. Strong safety guarantees ensure committed entries are never lost.',
    keyTakeaways: [
      { id: 'k1', text: 'Raft separates consensus into leader election, log replication, and safety — each easier to reason about than Paxos.' },
      { id: 'k2', text: 'A single leader accepts writes and replicates to followers, simplifying the data flow.' },
      { id: 'k3', text: 'Terms provide a logical clock that prevents stale leaders from corrupting state.' },
      { id: 'k4', text: 'Commit requires majority replication, guaranteeing durability across failures.' },
    ],
    importantQuotes: [
      { id: 'q1', text: 'Raft uses a randomized election timeout to reduce the likelihood of split votes.', page: 6 },
      { id: 'q2', text: 'A log entry is committed once it is stored on a majority of servers and the leader has stored all preceding entries.' },
    ],
    suggestedQuestions: [
      'How does Raft handle network partitions with a minority quorum?',
      'What are the trade-offs of joint consensus during membership changes?',
      'How does Multi-Raft (TiKV, CockroachDB) scale Raft across shards?',
    ],
    generatedDate: '2024-06-21T09:00:00Z',
    tags: [TAGS.systems, TAGS.research],
    model: 'rw-summarizer-v2',
  },
  {
    id: 's3',
    resourceId: 'r7',
    resourceTitle: 'Attention Is All You Need',
    workspaceId: 'ws4',
    workspaceName: 'NLP & Transformers',
    title: 'Transformers — Self-Attention Foundations',
    summary:
      'The Transformer architecture replaces recurrence with self-attention, enabling fully parallel training and stronger long-range modeling. Multi-head attention lets the model attend to different representation subspaces simultaneously. Positional encodings inject order information. The encoder-decoder structure with residual connections and layer normalization scales efficiently.',
    keyTakeaways: [
      { id: 'k1', text: 'Self-attention removes recurrence, enabling parallel computation across sequence positions.' },
      { id: 'k2', text: 'Multi-head attention captures relationships in different representation subspaces.' },
      { id: 'k3', text: 'Scaled dot-product attention is efficient via matrix multiplication.' },
      { id: 'k4', text: 'Sinusoidal positional encodings provide relative position without learned parameters.' },
    ],
    importantQuotes: [
      { id: 'q1', text: 'Attention is all you need — we propose a new simple network architecture based solely on attention mechanisms.', page: 1 },
      { id: 'q2', text: 'Multi-head attention allows the model to jointly attend to information from different representation subspaces.' },
    ],
    suggestedQuestions: [
      'Why does scaling by √d_k stabilize dot-product attention?',
      'How do learned vs sinusoidal positional encodings compare?',
      'What motivated the shift from LSTMs to attention for sequence modeling?',
    ],
    generatedDate: '2024-06-13T10:30:00Z',
    tags: [TAGS.nlp, TAGS.ai, TAGS.research],
    model: 'rw-summarizer-v2',
  },
  {
    id: 's4',
    resourceId: 'r8',
    resourceTitle: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP',
    workspaceId: 'ws4',
    workspaceName: 'NLP & Transformers',
    title: 'RAG — Parametric + Non-Parametric Memory',
    summary:
      'RAG combines a parametric language model with a non-parametric retriever over an external knowledge store. At inference, relevant documents are retrieved and conditioned on, grounding generation in updatable knowledge. This reduces hallucination, enables knowledge updates without retraining, and improves performance on open-domain QA.',
    keyTakeaways: [
      { id: 'k1', text: 'RAG retrieves documents at inference time, grounding generation in external knowledge.' },
      { id: 'k2', text: 'Knowledge can be updated by editing the document store — no model retraining required.' },
      { id: 'k3', text: 'Reduces hallucination by citing retrieved evidence.' },
      { id: 'k4', text: 'RAG-sequence and RAG-token differ in how retrieved context is integrated per prediction.' },
    ],
    importantQuotes: [
      { id: 'q1', text: 'We introduce RAG models where the parametric memory is a pre-trained seq2seq model and the non-parametric memory is a dense vector index of Wikipedia.' },
    ],
    suggestedQuestions: [
      'How does RAG compare to fine-tuning on a knowledge corpus?',
      'What retrieval methods (sparse vs dense) work best for RAG?',
      'How do chunking and embedding dimension affect RAG quality?',
    ],
    generatedDate: '2024-06-29T15:00:00Z',
    tags: [TAGS.nlp, TAGS.ai, TAGS.data],
    model: 'rw-summarizer-v2',
  },
  {
    id: 's5',
    resourceId: 'r5',
    resourceTitle: 'Designing Data-Intensive Applications — Ch. 7',
    workspaceId: 'ws2',
    workspaceName: 'Distributed Systems',
    title: 'Transaction Isolation Levels Explained',
    summary:
      'Chapter 7 covers transaction isolation, from read-uncommitted to serializable. Each level prevents certain anomalies (dirty reads, non-repeatable reads, phantom reads, write skew) but not others. Serializable isolation can be achieved via actual serial execution, 2PL, or SSI. The chapter emphasizes that "serializable" claims in databases are often weaker than the standard.',
    keyTakeaways: [
      { id: 'k1', text: 'Read committed prevents dirty reads but allows non-repeatable reads.' },
      { id: 'k2', text: 'Snapshot isolation prevents non-repeatable reads but allows write skew.' },
      { id: 'k3', text: 'True serializability requires serial execution, 2PL, or SSI.' },
      { id: 'k4', text: 'Many databases labeled "serializable" actually offer weaker guarantees.' },
    ],
    importantQuotes: [
      { id: 'q1', text: 'The term serializable is often used loosely — many databases that claim to be serializable actually offer weaker guarantees.', page: 252 },
    ],
    suggestedQuestions: [
      'What is write skew and how does SSI detect it?',
      'When is 2PL preferable to SSI?',
      'How do MVCC and snapshot isolation interact?',
    ],
    generatedDate: '2024-06-26T10:00:00Z',
    tags: [TAGS.systems, TAGS.data],
    model: 'rw-summarizer-v2',
  },
  {
    id: 's6',
    resourceId: 'r6',
    resourceTitle: 'How Linear builds product',
    workspaceId: 'ws3',
    workspaceName: 'Product Strategy 2025',
    title: 'Linear on Craft & Opinionated Defaults',
    summary:
      'Karri Saarinen discusses how Linear prioritizes craft, speed, and opinionated defaults. The team invests heavily in design polish and performance, treating the editor and keyboard shortcuts as core product surface. Strong defaults reduce configuration burden and let the product feel coherent. Hiring for taste and giving engineers design literacy is key to execution quality.',
    keyTakeaways: [
      { id: 'k1', text: 'Invest in performance and polish as features, not nice-to-haves.' },
      { id: 'k2', text: 'Opinionated defaults reduce decision fatigue and keep the product coherent.' },
      { id: 'k3', text: 'Keyboard-first workflows signal respect for power users.' },
      { id: 'k4', text: 'Design literacy across engineers raises the floor of execution quality.' },
    ],
    importantQuotes: [
      { id: 'q1', text: 'Speed is a feature. If the product feels instant, people trust it.' },
    ],
    suggestedQuestions: [
      'How does Linear balance opinionated defaults with flexibility?',
      'What processes keep design quality high as the team scales?',
      'How do they measure "craft" as a product metric?',
    ],
    generatedDate: '2024-07-02T09:00:00Z',
    tags: [TAGS.product, TAGS.webdev],
    model: 'rw-summarizer-v2',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'summary_ready',
    title: 'AI summary ready',
    message: 'Your summary for "Attention Is All You Need" is ready to review.',
    timestamp: '2024-07-06T08:30:00Z',
    read: false,
  },
  {
    id: 'n2',
    type: 'resource_added',
    title: 'New resource added',
    message: 'Priya Sharma added "Interpretability in the Wild" to AI Safety Research.',
    timestamp: '2024-07-05T14:20:00Z',
    read: false,
  },
  {
    id: 'n3',
    type: 'member_joined',
    title: 'New member joined',
    message: 'Lena Park joined NLP & Transformers.',
    timestamp: '2024-07-03T10:00:00Z',
    read: true,
  },
  {
    id: 'n4',
    type: 'mention',
    title: 'You were mentioned',
    message: 'Daniel Kim mentioned you in a comment on "Alignment Taxonomy v2".',
    timestamp: '2024-07-01T16:45:00Z',
    read: true,
  },
];

export const mockProfile: Profile = {
  user: mockUser,
  totalWorkspaces: 4,
  savedResources: 113,
  aiSummariesGenerated: 84,
  preferences: {
    emailNotifications: true,
    weeklyDigest: true,
    autoGenerateSummaries: true,
    defaultSummaryModel: 'rw-summarizer-v2',
    theme: 'light',
  },
};
